### ISSUE TITLE
Running snapUtil produces "fs_snapshot_create: Operation not permitted"

### ISSUE THREAD

**Issue by spitfire** [ahl/apfs#2]
Hi,
Even though I ran snapUtil with elevated permissions:
`sudo ./snapUtil -c first /Volumes/DATA01/`
I'm getting
`fs_snapshot_create: Operation not permitted`

`/Volumes/DATA01` is an APFS volume:
`/dev/disk3s1 on /Volumes/DATA01 (apfs, local, nodev, nosuid, journaled, noowners)`

Does this require disabling SIP?

I'm running macOS 10.14:
`Darwin MMBP.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

**Comment by kevpatt** [comment]
I have SIP disabled and it still doesn't work.

**Comment by kevpatt** [comment]
I believe the app needs a specific entitlement (I think it is com.apple.developer.vfs.snapshot) to be added during code signing. That needs to be requested from Apple Developer Tech Support AFAIK.

**Comment by yeahdongcn** [comment]
Do you know how to include an entitlement file into a command-line application on macOS?

**Comment by mroi** [comment]
You can manually create an entitlements plist file and then pass this file to the code signing process:
```
codesign -s $(id -F) --entitlements snapUtil.entitlements snapUtil
```

I tried using both `com.apple.developer.vfs.snapshot` (as mentioned above) and `com.apple.private.vfs.snapshot` (as used by Time Machine’s `backupd`), but neither worked. SnapUtil gets killed immediately when launched.

**Comment by mroi** [comment]
Just to amend my findings: the Arq backup utility legitimately uses APFS snapshots. It has the `com.apple.developer.vfs.snapshot` entitlement assigned, endorsed by an embedded Apple-signed provisioning profile.

**Comment by yeahdongcn** [comment]
It looks like one needs to do a special request to Apple for the provisioning profile.

**Comment by mroi** [comment]
I managed to run it on Catalina with these two steps:
1. I added the `com.apple.developer.vfs.snapshot` entitlement when signing the binary. Even ad-hoc signing works.
2. I rebooted to recovery and disabled SIP and AMFI with the commands `csrutil disable` and `nvram boot-args= amfi_get_out_of_my_way=0x1`.

After booting back to macOS proper, I can run `snapUtil` and create and manage snapshots. You can then reenable security with `csrutil enable` and `nvram -d boot-args`.

**Comment by sclsj** [comment]
You also need the entitlement `com.apple.private.apfs.revert-to-snapshot` to use `snaputil -r` functionality.

**Comment by sclsj** [comment]
@mroi I still think that you cannot re-enable AMFI as it will check the code signature, realise it's not from Apple, and KILL the process. Can you check if AMFI actually allows ad-hoc code signature with entitlements?

**Comment by mroi** [comment]
Maybe my wording was confusing: I can also only use `snapUtil` when AMFI is disabled. I just meant that (obviously) any snapshots you create on the volume remain when re-enabling AMFI. Thanks for the hint with the revert entitlement.

**Comment by airhorns** [comment]
Has anyone figured out a way to grant yourself these entitlements to use on an ongoing basis without disabling SIP and AMFI permanently? https://github.com/osy/AMFIExemption looked promising but doesn't support arm-based macs.

**Comment by yadvr** [comment]
Does this work on newer macOS?

**Comment by mroi** [comment]
Yes. I am running Tahoe (macOS 26) on Apple Silicon and the [steps in the above comment](#issuecomment-692676040) still work.

The only slight twist is that setting `nvram boot-args` can no longer be done from within recovery, but can be done in regular macOS once SIP is disabled (i.e. after `csrutil disable`). So you have to reboot once into recovery, disable SIP, reboot again into macOS proper, disable AMFI, and then reboot yet again. After this procedure you can run `snapUtil`.

**Comment by yadvr** [comment]
Thanks @mroi I've disabled SIP and then AMFI rebooted the system; ~~I still get the same error. Is the codesign step mandatory?~~

It worked after running codesign on it:

```
> cat snapUtil.entitlements
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.vfs.snapshot</key>
	<true/>
</dict>
</plist>

> codesign --force --sign - --entitlements snapUtil.entitlements snapUtil

```

**Comment by mroi** [comment]
Yes, the entitlement is required. AMFI just causes the entitlement to be ignored unless the binary is signed by Apple. That’s why AMFI must be off.

**Comment by sclsj** [comment]
> Yes, the entitlement is required. AMFI just causes the entitlement to be ignored unless the binary is signed by Apple. That’s why AMFI must be off.

More accurately, AMFI just kills the process if it's not validly signed.

**Comment by mroi** [comment]
> More accurately, AMFI just kills the process if it's not validly signed.

Oh yes, thanks for catching this. My mistake.
